# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
id = "mboldt/utility-buildpack"
version = "0.0.1"
name = "Utility Buildpack"
homepage = "https://github.com/mboldt/utility-buildpack-plumbing"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"

[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
