name: Tests
"on":
    pull_request: {}
    push:
        branches:
            - main
jobs:
    unit:
        name: Unit Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                path: ${{ env.HOME }}/go/pkg/mod
                restore-keys: ${{ runner.os }}-go-
            - uses: actions/setup-go@v3
              with:
                go-version: "1.17"
            - name: Run Tests
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                make unit
